#-------------------------------------------------------------------------------
#     _    ____   ____ _   _ ___ ____  _____ ____  
#    / \  |  _ \ / ___| | | |_ _|  _ \| ____|  _ \ 
#   / _ \ | |_) | |   | |_| || || | | |  _| | |_) |
#  / ___ \|  _ <| |___|  _  || || |_| | |___|  _ < 
# /_/   \_\_| \_\\____|_| |_|___|____/|_____|_| \_\
#
#             .--. 
#            |o_o |       RESUME: basic terminal settings: cursor, scrolling & selection
#            |:_/ |      
#           //   \ \       
#          (|     | )      AUTHOR: Haidex3
#         /'\_   _/`\      URL: https://github.com/Haidex3/Archider
#         \___)=(___/      
#
#-------------------------------------------------------------------------------#/
                                            
[general]
import = ["~/.config/alacritty/colors.toml"]

[colors.cursor]
text = "#1E1E3F"
cursor = "#FAD000"

[colors.normal]
black   = "#000000"
red     = "#EC3A37"
green   = "#75E44C"
yellow  = "#FAD000"
blue    = "#6943FF"
magenta = "#FF2C70"
cyan    = "#80FCFF"
white   = "#c88bad"

[colors.bright]
black   = "#5C5C61"
red     = "#EC3A37"
green   = "#23c887"
yellow  = "#FAD000"
blue    = "#6943FF"
magenta = "#FB94FF"
cyan    = "#2cb4d9"
white   = "#2D2B55"
[window]
opacity = 1.0
decorations = "Full"

[window.padding]
x = 4
y = 4

[cursor]
style = "Beam"
blink_interval = 500
unfocused_hollow = false

[scrolling]
history = 10000
multiplier = 3

[bell]
duration = 0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[[hints.enabled]]
regex = "(https?|ftp)://[^\\s]+"
command = "xdg-open"
post_processing = true
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }

[env]
TERM = "xterm-256color"
